[project]
name = 'Decentralized-Disaster-Recovery-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.needs-assessment]
path = 'contracts/needs-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-registration]
path = 'contracts/resource-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
